#!/usr/bin/python2.7

#This is just a test script.
#The idea is to verify that the c/c++ code
#can validate a password hash generated by
#python bcrypt. The python and c/c++ versions
#are essentially directly from the openbsd
#implementation

#on ubuntu
#sudo apt-get install python-pip python-dev build-essential
#sudo pip install --upgrade pip
#sudo pip install --upgrade virtualenv
#sudo pip install bcrypt

import bcrypt
import sys

quote_chars = ["\"", "'"]

for arg in sys.argv:
        if arg.split("=")[0] == "password":
                password = arg.split("=")[1]

if password[0] in quote_chars:
    password = password[1:]
if password[-1] in quote_chars:
    password = password[0:-2]


hashed = bcrypt.hashpw(password, bcrypt.gensalt())
hashed = hashed.replace('$2a$', '$2y$')

#print 'encrypted pw'
#print '\n'
#print str(hashed)
#print hashed

sys.stdout.write(hashed)
