#!/usr/bin/python3

#This is just a test script.
#The idea is to verify that the c/c++ code
#can validate a password hash generated by
#python bcrypt. The python and c/c++ versions
#are essentially directly from the openbsd
#implementation

#on ubuntu
#sudo apt-get install python-pip python-dev build-essential
#sudo pip install --upgrade pip
#sudo pip install --upgrade virtualenv
#sudo pip install bcrypt

import bcrypt
import sys

quote_chars = ["\"", "'"]

for arg in sys.argv:
        if arg.split("=")[0] == "password":
                password = arg.split("=")[1]

if password[0] in quote_chars:
    password = password[1:]
if password[-1] in quote_chars:
    password = password[0:-2]


hashed = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt())

fix_str1_to_hash = '$2a$'

fix_str2_to_hash = '$2y$'


hashed = hashed.replace(fix_str1_to_hash.encode('utf-8'), fix_str2_to_hash.encode('utf-8'))

#print 'encrypted pw'
#print '\n'
#print str(hashed)
#print hashed

sys.stdout.write(str(hashed.decode('utf8')))
